config/routes.rb
Rails.application.routes.draw do
  resources :importing_units, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/unit.rb
class Unit < ApplicationRecord
  @@csv_data
  def self.csv?
    true
  end

  def self.csv_data=(value)
    @@csv_data = value
  end

  def self.csv_data
    @@csv_data
  end

  def self.mapped_columns
    {
      'name' => 'name',
      'description' => 'description',
      'area' => 'area',
      'price' => 'price',
      'unit_type' => 'uom'
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/importing_units_controller.rb
class ImportingUnitsController < ApplicationController
  def index
    @units = Unit.all
  end

  def new
  end

  def create
    Unit.csv_data = params[:file].read
    result_context = Etl::Parse.call(Unit)

    respond_to do |format|
      if result_context.success?
        format.html { redirect_to importing_units_path, notice: 'Units were successfully imported.' }
      else
        format.html do
          flash[:error] = result_context.message
          render :new
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/importing_units/_form.html.erb
<%= form_with(url: importing_units_path, local: true) do |form| %>
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %>

  <div>
    <%= form.file_field :file %>
  </div>
  <br />
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/importing_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <th>
          name
        </th>
        <th>
          description
        </th>
        <th>
          area
        </th>
        <th>
          uom
        </th>
        <th>
          price
        </th>
      </tr>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.description %></td>
        <td><%= unit.area %></td>
        <td><%= unit.uom %></td>
        <td><%= unit.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Import Units', new_importing_unit_path %>

app/views/importing_units/new.html.erb
<h1>Import Units</h1>

<%= render 'form' %>

<br />
<%= link_to 'Back', importing_units_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EtlStarterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>